name: Deploy Site

on:
  schedule:
    - cron: '*/30 * * * *'

  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    env:
      API_URL: https://api.cobalt.seika.computer
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-actions

      - name: Get API Commit
        id: commit
        run: echo "commit=$(curl -fsSL --retry 5 --retry-delay 5 ${{ env.API_URL }} | jq -r .git.commit)" >> ${GITHUB_OUTPUT}

      - name: Clone imputnet/cobalt
        uses: actions/checkout@v4
        with:
          repository: imputnet/cobalt
          ref: ${{ steps.commit.outputs.commit }}
          path: cobalt

      - name: Set Up pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: cobalt/package.json

      - name: Build Site
        run: pnpm install --filter @imput/cobalt-web && pnpm build --filter @imput/cobalt-web
        working-directory: cobalt/web
        env:
          WEB_DEFAULT_API: ${{ env.API_URL }}
          WEB_HOST: https://cobalt.seika.computer

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: cobalt/web/build

  deploy:
    name: Deploy Site
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
